//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace fbpm.Models
{
    public partial class FlatDetail
    {
        public string FlatID { get; set; }
        public string ProjectID { get; set; }
        public Nullable<long> SuperBuiltUpArea { get; set; }
        public byte[] LayoutImg { get; set; }
        public string ProjectDetailProjectID { get; set; }
    
        public virtual ProjectDetail ProjectDetail { get; set; }
    }
    
}
