//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace fbpm.Models
{
    public partial class FlatDetail
    {
        [Display(Name = "Flat ID")]
        public string FlatID { get; set; }
        [Display(Name = "Project ID")]
        public string ProjectID { get; set; }
        [Display(Name = "Super Built Up Area")]
        public Nullable<long> SuperBuiltUpArea { get; set; }
        [Display(Name = "Layout Image")]
        public byte[] LayoutImg { get; set; }
        public string ProjectDetailProjectID { get; set; }
    
        public virtual ProjectDetail ProjectDetail { get; set; }
    }
    
}
