//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace fbpm.Models
{
    public partial class PaymentSchedule
    {
        [Display(Name="Schedule ID")]
        public System.Guid ScheduleID { get; set; }
        [Display(Name = "User ID")]
        public string UserID { get; set; }
        [Display(Name = "Schedule Description")]
        public string ScheduleText { get; set; }
        [Display(Name = "Schedule Date")]
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        [Display(Name = "Schedule Percentage")]
        public Nullable<int> SchedulePercentage { get; set; }
        [Display(Name = "Booked Date")]
        public Nullable<System.DateTime> BookedDate { get; set; }
        [Display(Name = "Booking Amount")]
        public Nullable<decimal> BookingAmount { get; set; }
        [Display(Name = "Schedule Amount ")]
        public Nullable<decimal> ScheduleAmount { get; set; }
        [Display(Name = "Remaining Amount")]
        public Nullable<decimal> RemainingAmount { get; set; }
        public string UserDetailsUserID { get; set; }
    
        public virtual UserDetails UserDetail { get; set; }

        public IEnumerable<UserDetail> UserDetailList { get; set; }
    }
    
}
