//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace fbpm.Models
{
    public partial class ProjectDetail
    {
        public ProjectDetail()
        {
            this.FlatDetails = new HashSet<FlatDetail>();
            this.ProjectSchedules = new HashSet<ProjectSchedule>();
        }
    
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> NoOfBlocks { get; set; }
        public Nullable<int> NoOfFloors { get; set; }
        public Nullable<long> NoOfFlats { get; set; }
        public string Amenities { get; set; }
    
        public virtual ICollection<FlatDetail> FlatDetails { get; set; }
        public virtual ICollection<ProjectSchedule> ProjectSchedules { get; set; }
    }
    
}
