//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace fbpm.Models
{
    public partial class ProjectSchedule
    {
        public int ScheduleID { get; set; }
        public string ProjectID { get; set; }
        public string ScheduleText { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> SchedulePercentage { get; set; }
        public string ProjectDetailProjectID { get; set; }
    
        public virtual ProjectDetail ProjectDetail { get; set; }
    }
    
}
