//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace fbpm.Models
{
    public partial class UserDetails
    {
        public UserDetails()
        {
            this.PaymentSchedules = new HashSet<PaymentSchedule>();
        }
    
        public string UserID { get; set; }
        public string Password { get; set; }
        public string EmailID { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string FullAddress { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> Role { get; set; }
        public string PANNo { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> BookedDate { get; set; }
        public Nullable<decimal> BookedAmount { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<PaymentSchedule> PaymentSchedules { get; set; }
    }
    
}
